# theme 的配置，页面上取字段 theme 

colors:
    - 
        name: bg
        value: '#EBD7C3'
    - 
        name: orange
        value: '#D17028'
    - 
        name: green
        value: '#809181'
    - 
        name: orange2
        value: '#E7B67B'
    - 
        name: blank
        value: '#313C3E'

        